### PR TITLE
Added the search functionality

### PR DESCRIPTION
**Pull request by KARANSINGH34951**
Added a full dynamic search functionality to search through the leaderboard and also update the gitignore file. Pls merge the request as soon as possible i will be start work on other issues in the leaderboard.

Before:(With search bar functionality)
Screenshot 2024-10-01 220712

After :

https://github.com/user-attachments/assets/bbe2b633-57d8-417b-a3fa-ee05430fd3c4

### CODE REVIEW

**Comment by swamimalode07** [comment]
Make sure you resolve conflics in this code , so i can merge it

**Comment by swamimalode07** [comment]
and why is it not showing the previos users , did you use local backend?

**Comment by KARANSINGH34951** [comment]
> and why is it not showing the previos users , did you use local backend?

yes, i have used the local backend for testing pls change to mongo atlas and it will be fine.

**Comment by swamimalode07** [comment]
Make sure you resolve the conflicts so i can merge your code

**Comment by swamimalode07** [comment]
also dont change the app.cjs code and just test the website with my mongo backend

**Comment by KARANSINGH34951** [comment]
I have fixed the env and app.js error if still you are facing error let me know and specify the error.

**Comment by swamimalode07** [comment]
can youplpease resolve the conflicts and not make any changes in the app.cjs and database

**Pull request closed without merging**
