### PR TITLE
UI Improvement in Leaderboard page #3

### PR DESCRIPTION
**Pull request by KARANSINGH34951**
Before : The UI 
Screenshot 2024-10-08 001422

After :

Screenshot 2024-10-08 001939

### CODE REVIEW

**Comment by KARANSINGH34951** [comment]
Hii @swamimalode07 ,I hope you’re doing well. I wanted to follow up on the pull request I submitted yesterday.

**Comment by swamimalode07** [comment]
I love the changes you made , just make sure you dont change colors and UI consistency of the website @KARANSINGH34951

**Comment by KARANSINGH34951** [comment]
Thank you @swamimalode07 ,Can you be more specific what color are you talking about, just need clarity on the colors and UI consistency of the website.

**Comment by swamimalode07** [comment]
Check the present leaderboard and check the colors , and for top 3 players add proper golden silver and bronze color like i've done for top 1st player that's linear gradient

**Comment by KARANSINGH34951** [comment]
Pls Have a look, I have done the following adjustments that follows colors and UI consistency of the website.
image

**Comment by swamimalode07** [comment]
make the user icons white and resolve the conflicts , it's looking good and i will merge it

**Comment by swamimalode07** [comment]
Dont forget to keep it responsive

**Comment by KARANSINGH34951** [comment]
All changes are done and added responsiveness too

**Comment by swamimalode07** [comment]
there are some conflicts can you resolve them so i can merge

**Comment by KARANSINGH34951** [comment]
Is this Pull request merged Now ?

**Pull request closed without merging**
