### PR TITLE
adding play again button

### PR DESCRIPTION
**Pull request by rahulchaudhary2244**
This update introduces a "Play Again" button to the leaderboard's navbar, enhancing user experience by allowing easy navigation to start a new game without needing to use the browser's back button.

This PR closes issue - https://github.com/swamimalode07/SimonsaysGame/issues/7

https://github.com/user-attachments/assets/4bdbce88-a3ea-4ead-812b-1fd937465bab

### CODE REVIEW

**Comment by rahulchaudhary2244** [comment]
Hi @swamimalode07 , Could you please take a look at my PR when you have some time? Also, it would be great if you could add the ```hacktoberfest-accepted``` label to ensure it gets counted for the event.

**Comment by swamimalode07** [comment]
YEah sure ,just resolve the conflicts and if you used local database , please make it like it was before

**Comment by rahulchaudhary2244** [comment]
Hi @swamimalode07, I've resolved the conflicts. Could you please take another look when you have a moment?

**Comment by swamimalode07** [comment]
U did not change the database right

**Comment by rahulchaudhary2244** [comment]
no

**Comment by swamimalode07** [comment]
It has problems with responsiveness and also there comes a gap above the first user kindly fix it

**Pull request merged**
