### PR TITLE
navbar position fixed

### PR DESCRIPTION
**Pull request by rahulchaudhary2244**
During testing with a larger dataset on the leaderboard, I discovered that recent changes in [PR #38](https://github.com/swamimalode07/SimonsaysGame/pull/38/files) unintentionally impacted the navbar’s position. This PR addresses the issue and restores the navbar to its original layout and behavior.

### CODE REVIEW

**Comment by rahulchaudhary2244** [comment]
Hi @swamimalode07, Could you please take a look at my PR when you have some time? Also, it would be great if you could add the ```hacktoberfest-accepted``` label to ensure it gets counted for the event.

**Comment by rahulchaudhary2244** [comment]
I didn't make any changes to the database.

**Comment by swamimalode07** [comment]
can you attach screenshots of before and after PR

**Comment by rahulchaudhary2244** [comment]
Hi @swamimalode07 , I've implemented two different approaches to achieve responsiveness. Could you please review them and share your thoughts on which one would be the best to go with ?

## 1
https://github.com/user-attachments/assets/6c089b2a-def2-4533-a2a0-9b4c1670a3d7

## 2
https://github.com/user-attachments/assets/f715122f-ba0c-4619-a389-1b1639698e0f

**Comment by swamimalode07** [comment]
can you please remove the conflicts so i can merge your PR

**Pull request closed without merging**
