### PR TITLE
Enhancement of How to play pop up bar 

### PR DESCRIPTION
**Pull request by KARANSINGH34951**
#4 Improved the UI of pop Instruction for better user experience

UI Before :
Screenshot 2024-10-14 071049

UI Ater:
Screenshot 2024-10-14 070854

### CODE REVIEW

**Comment by swamimalode07** [comment]
can you resolve the conflicts and make sure you  make lesser changes in only  the parys required so the code remains clean

**Comment by KARANSINGH34951** [comment]
What is the root cause of these conflicts? (any idea)

**Comment by swamimalode07** [comment]
probabaly you have made changes in a branch that is not up to date

**Comment by swamimalode07** [comment]
delete the previos for and make a new and do changes in that and make sure the changes you do are responsive

**Pull request closed without merging**
